This Notebook is for numpy introduction and array manupulation as numpy is a powerful 
Computation library.

importing needed libraries

# Introduction and basics

In [2]:
import numpy as np
import matplotlib.pyplot as plt

%matplotlib inline

In [3]:
np.__version__

'1.21.6'

Getting started with arrays.

In [4]:
# empty array gives random changing values
np.empty(2)

array([0., 0.])

In [5]:
# Seeding for reproducibility
np.random.seed(3)

In [6]:
np.random.randint(7, size=6) 

array([2, 0, 1, 3, 0, 0])

In [7]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [8]:
# Shape of the array
a.shape

(3, 4)

In [9]:
# data types of numpy array
a.dtype


dtype('int64')

In [11]:
# Knowing the size covered by the array
print(f' a is {a.itemsize} bytes each element')
print(f'a is {a.nbytes} bytes size')

 a is 8 bytes each element
a is 96 bytes size


# Array Operations

Indexing

In [12]:
# Getting the first element of the array
a[0]

array([1, 2, 3, 4])

In [13]:
# Getting the 1th element from first array
a[0][1]

2

In [14]:
# Getting the last element
a[-1]

array([ 9, 10, 11, 12])

In [16]:
# Can also access elements using a comma separated indexing
print(a[2, 1])
print(a[2, -1])

10
12


Reversing the array

In [18]:
data = np.arange(12)
print(data)

[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [19]:
# Reversing the array
data[::-1]

array([11, 10,  9,  8,  7,  6,  5,  4,  3,  2,  1,  0])

In [20]:
# Slicing
data[2:6]

array([2, 3, 4, 5])

In [21]:
# Every other elements starting from index 3 with step of 4
data[3::4]

array([ 3,  7, 11])

Slicing a Multidimensional array

In [22]:
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [25]:
# Slicing first 2 elements starting from index 2
a[:2, :2]

array([[1, 2],
       [5, 6]])

In [27]:
# Reversing a sliced part of an array
a[:1, ::-1]

array([[4, 3, 2, 1]])

Reshaping arrays

In [29]:
x = np.arange(1, 16).reshape((3, 5))
print(x)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]


In [30]:
x.reshape((5, 3))

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15]])

In [31]:
# Shaping to (15, 1)
x.reshape(15)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [35]:
new_arr = np.array([0, 2, 6, 7])
print(new_arr)

[0 2 6 7]


In [36]:
# Reshaping new_arr
new_arr.reshape(1, 4)

array([[0, 2, 6, 7]])

In [38]:
# Row vector via new axis
new_arr[np.newaxis, :]

array([[0, 2, 6, 7]])

In [37]:
# Column vector via newaxis
new_arr[:, np.newaxis]

array([[0],
       [2],
       [6],
       [7]])

# Some typical example of numpy arrays application